### ISSUE TITLE
Escape browser templates

### ISSUE THREAD

**Issue by nmocruz** [express-handlebars/express-handlebars#101]
Hi, 

I was thinking in render with html templates
So the idea is my view could have a html template that could be fully escaped
```
{{user,name}}
<template id='client-template' >
  Hi, am a browser template, maybe reactivejs
  {{message}}
</tempale>

<script>
const ractive = Ractive({
  el: 'body',
  data: {
    message: 'Hello World!'
  },
 template: document.getElementById('client-template')
})
</script>

```

I know that I can do \{{message}}, theres any way to escape an all block

**Comment by UziTech** [comment]
I'm not exactly sure what you are trying to accomplish but this sounds like a question for [handlebars](https://github.com/handlebars-lang/handlebars.js).

express-handlebars is middleware to render with handlebars in express. express-handlebars doesn't do anything in the actual render process.

**Comment by nmocruz** [comment]
I will ask to them.
