### ISSUE TITLE
Question: how can I trigger a server side action through an onclick event?

### ISSUE THREAD

**Issue by fakob** [express-handlebars/express-handlebars#111]
Hi, 
I am trying to trigger a server side action through a button click, but failed. Maybe I have misunderstood how this should work.
I am passing an action to the template. 
```
app.get("/", function (req, res) {
  res.render("home", {
    action: () => {
      return serverSideAction();
      // return () => serverSideAction();
    }
  });
});

const serverSideAction = () => {
  console.log("serverSideAction");
};
```
and in the template I want to call.
```
<button type="button" onclick="{{this.action}}">click</button>
```
I have tried passing it in different ways, but it always only gets called when loading the page. The onclick event is empty.
By now you have seen that I am a noobie, but as I had searched quite a bit and have not found any help, I hope that anyone here can point me into the right direction. I wonder what I am doing wrong?

Here is a simple sandbox example: https://codesandbox.io/s/express-handlebars-onclick-event-9zb3x

**Comment by UziTech** [comment]
You cannot pass a function in handlebars. You will need to use javascript. stackoverflow.com is a better place for these types of questions.

**Comment by fakob** [comment]
Thanks @UziTech, good to know. Will do.
