### ISSUE TITLE
External hbs file

### ISSUE THREAD

**Issue by impactcolor** [express-handlebars/express-handlebars#118]
How would i load a file from an external source?
In my case "external" means `localhost:1337/uploads/myFile.hbs`

**Comment by UziTech** [comment]
You would have to fetch the file and copy it locally.

**Comment by impactcolor** [comment]
Pulling the code with let's say Axios would the setup be:
`res.render('home', {layout: dataresponseHere});`
?
@UziTech

**Comment by UziTech** [comment]
No you will have to save it as a file then use express-handlebars like normal.

Alternatively you can just use [handlebars](https://handlebarsjs.com/installation/) without express-handlebars.

something like:

```js
const template = Handlebars.compile(hbs);
res.send(template(data));
```
