### ISSUE TITLE
document covering installation options

### ISSUE THREAD

**Issue by blachawk** [express-handlebars/express-handlebars#137]
In regards to installing this project via npm, is express-handlebars **needed** to run at runtime (dependency)? or is this project only required to be in used during development (dev-dependency)?

**Comment by UziTech** [comment]
It is needed as a middleware for express. You can see the example in the readme.

```js
var express = require('express');
var exphbs  = require('express-handlebars');

var app = express();

app.engine('handlebars', exphbs());
app.set('view engine', 'handlebars');

app.get('/', function (req, res) {
    res.render('home');
});

app.listen(3000);
```

**Comment by blachawk** [comment]
so if its middleware for express, would it be ok to install this as a devdependency?

**Comment by UziTech** [comment]
Basically if you have a build step that bundles your server side code it can be a `dev-dependency`. If you don't have a build step for your server side code it will have to be a `dependency` or it will not install on the production sever.
