### ISSUE TITLE
Multiple named blocks inside layouts

### ISSUE THREAD

**Issue by BokChoyWarrior** [express-handlebars/express-handlebars#169]
Hi, is there any way to have multiple named blocks inside layouts?

**Comment by UziTech** [comment]
What do you mean multiple named blocks? Have you tried something that didn't work?

**Comment by BokChoyWarrior** [comment]
Well, for now, the only "block" you can utilise is `{{{body}}}`. 
I am coming from Jinja2 where we can define a block with any name, for instance I would have a block called `{{{javascript}}}` in case a particular page needed some extra functionality. The child layout/template would then pick and choose which blocks to "fill-in". 

The page [here](https://jinja.palletsprojects.com/en/2.11.x/templates/#template-inheritance) will give you a better explanation than I could .

Thanks
