### ISSUE TITLE
Your types deffinition does not align with latest

### ISSUE THREAD

**Issue by adonisv79** [express-handlebars/express-handlebars#17]
I am defining 'defaultView' for the ExphbsOption and get the error that it does not exist. there exists a 'defaultLayout' property though. however if I use that, runing the code triggers a failure of 

```
No default engine was specified and no extension was provided.
```

**Comment by UziTech** [comment]
Can you share your exact setup code? Are you calling `app.engine()`?

**Comment by adonisv79** [comment]
sorry, I decided to use hbs instead after that. but basically I just followed the basic guide from [here](https://medium.com/@waelyasmina/a-guide-into-using-handlebars-with-your-express-js-application-22b944443b65)

```
app.engine('hbs', handlebars({
layoutsDir: __dirname + '/views/layouts',
extname: 'hbs',
//new configuration parameter
defaultLayout: 'planB',
}));
app.get('/', (req, res) => {
//instead of res.render('main', {layout: 'index'});
res.render('main');
});
```

**Comment by UziTech** [comment]
What do you mean by "Your types definition"? We don't provide any type definitions.

**Comment by adonisv79** [comment]
https://www.npmjs.com/package/@types/express-handlebars

**Comment by adonisv79** [comment]
I do typescript FYI ;)

**Comment by UziTech** [comment]
I see, you should open an issue or PR on https://github.com/DefinitelyTyped/DefinitelyTyped
