### ISSUE TITLE
Error messages don't display useful information

### ISSUE THREAD

**Issue by Kewyn-Vieira** [express-handlebars/express-handlebars#192]
I've been getting " The partial header could not be found " and I always have no idea where the program is trying to look for the file and I end up just trying to guess a bunch of paths until I find the right one.

It would be useful if the error message were displayed like " The partial header could not be found in 'failed/path/to/file' "

**Comment by akhimchak** [comment]
any feedback on this?

**Comment by UziTech** [comment]
This seems like something that would have to change in handlebars.

**Comment by UziTech** [comment]
closing as this is a handlebars issue
