### ISSUE TITLE
handlbars.moment or handlebars-helpers - registerHelper()

### ISSUE THREAD

**Issue by jondo89** [express-handlebars/express-handlebars#20]
THIMC , 

Could you provide an example of the integration of express-handlbars and any of the popular helper npm modules .

ideally handlbars.moment or handlebars-helpers.

I am unable to access the regiterHelper function to pass into express-handlbars to expose the helpers for moment .

Thanks a million !

**Comment by claytonc** [comment]
I set up like this

```
const exphbs = require('express-handlebars');
const handlebarsHelpers = require('handlebars-helpers')();
const momentHandler = require('handlebars.moment')();

app.engine(
  "hbs",
  exphbs({
    extname: "hbs",
    defaultLayout: false,
    helpers: Object.assign({}, handlebarsHelpers, momentHandler)
  })
);
```

**Comment by andresilva-cc** [comment]
> I set up like this
> 
> ```
> const exphbs = require('express-handlebars');
> const handlebarsHelpers = require('handlebars-helpers')();
> const customHelpers = require(path.join(process.cwd(), 'src', 'helpers', 'helpers.js'));
> 
> app.engine(
>   "hbs",
>   exphbs({
>     extname: "hbs",
>     defaultLayout: false,
>     helpers: Object.assign({}, handlebarsHelpers, customHelpers)
>   })
> );
> ```

It's not working:

```js
// Handlebars helpers
const handlebarsMoment = require('handlebars-helper-moment')()

// Create Express instance
const app = express()

// View engine setup
app.engine('handlebars', exphbs({
  helpers: Object.assign({}, handlebarsMoment)
}))
```

And in view:
```hbs
<td>\{{moment format="DD/MM/YYYY"}}</td>
```

It just returns ```\{{moment format="DD/MM/YYYY"}}``` instead of the formatted date.

**Comment by UziTech** [comment]
@andresilva-cc I believe `\{{` tells handlebars to escape the braces and make them act like html not a placeholder.

If you want a slash in front of the placeholder try `\\{{`

**Comment by andresilva-cc** [comment]
> @andresilva-cc I believe `\{{` tells handlebars to escape the braces and make them act like html not a placeholder.
> 
> If you want a slash in front of the placeholder try `\\{{`

I put \ because in handlebars-helper-moment documentation they were using it. But I gave up and created my own custom helper using moment.

**Comment by UziTech** [comment]
> I put \ because in handlebars-helper-moment documentation they were using it.

That looks like an issue with their documentation. it seems to work fine without the slash.

**Comment by claytonc** [comment]
> 
> It's not working:
> 
> ```js
> // Handlebars helpers
> const handlebarsMoment = require('handlebars-helper-moment')()
> 
> // Create Express instance
> const app = express()
> 
> // View engine setup
> app.engine('handlebars', exphbs({
>   helpers: Object.assign({}, handlebarsMoment)
> }))
> ```
> 
> And in view:
> 
> ```
> <td>\{{moment format="DD/MM/YYYY"}}</td>
> ```
> 
> It just returns `\{{moment format="DD/MM/YYYY"}}` instead of the formatted date.

I tested it like this, and it is working:

```
const handlebarsMoment = require('handlebars-helper-moment')()

app.engine(
  "hbs",
  exphbs({
    extname: "hbs",
    defaultLayout: false,
    helpers: Object.assign({}, handlebarsMoment)
  })
);
```
{{moment format="DD/MM/YYYY"}}

Do not use handlebars-helpers and handlebars-helper-moment together, as both have the 'moment' helper.

**Comment by UziTech** [comment]
closing as stale
