### ISSUE TITLE
Add footer and other template in main file

### ISSUE THREAD

**Issue by prasantdev** [express-handlebars/express-handlebars#207]
├── app.js
└── views
---├── home.handlebars
---├── footer2.handlebars
---└── layouts
------├── main.handlebars
------└── footer1.handlebars

Can I include `footer` from `footer1.handlebars` or `footer2.handlebars` in `main.handlebars` ?

`main.handlebars`
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Example App</title>
</head>
<body>

    {{{body}}}

 //Footer here

</body>
</html>
```

**Comment by UziTech** [comment]
You can use [partials](https://handlebarsjs.com/guide/#partials)

**Comment by prasantdev** [comment]
> You can use [partials](https://handlebarsjs.com/guide/#partials)

Thank you so much ❤
