### ISSUE TITLE
Error: Cannot find module './types'

### ISSUE THREAD

**Issue by BuiTanLan** [express-handlebars/express-handlebars#235]
Hi @ericf , I cannot my run project because there is no types.d.ts file of this package in  dist folder. Please fix this bug soon, thanks

**Comment by UziTech** [comment]
PRs are welcome 😁👍

**Comment by alanespinet** [comment]
Hello, I am having the same problem, but only with version 6 of the package. I used version 5.3.5 instead and it worked perfectly. Thank you very much
