### ISSUE TITLE
res.render from subdirectory in views

### ISSUE THREAD

**Issue by KrisLau** [express-handlebars/express-handlebars#239]
I'm trying to render my view from my `emails` subdirectory but I cant seem to get it to work. To clarify, I don't want to change the default directory for handlebars and I just want to change it for this path.

Directory:
`views/emails/invite.handlebars`

Code:
```
router.get('/', (req, res) => {
    res.render('emails/invite.handlebars', {layout: false});
});
```

Error: `Failed to lookup view "emails/invite.handlebars" in views directory "./views"`

Other things I've tried:
- `/emails/invite.handlebars`
- `../views/emails/invite.handlebars`

**Comment by UziTech** [comment]
What version are you using?

**Comment by UziTech** [comment]
Can you try adding `app.set("views", path.resolve(__dirname, "./views"));`?
see the [basic example](https://github.com/express-handlebars/express-handlebars/blob/master/examples/basic/server.js) for an example

**Comment by KrisLau** [comment]
@UziTech Hmm I'm not sure why but I just gave it another go (without changing anything) and it suddenly worked 😅 Really sorry for the trouble!
