### ISSUE TITLE
Expecting 'ID', got 'INVALID'

### ISSUE THREAD

**Issue by snowy1000** [express-handlebars/express-handlebars#24]
I get the following error when I try to use code belove:
This is the code I use: `<div class="text-dark font-weight-bold h5 mb-0"><span>{{bot.users.cache.get("300573341591535617")}}</span></div>`

Error is: `Expecting 'ID', got 'INVALID'`

Output of `{{log bot.users.cache}}` is: https://hasteb.in/ageyaxin.yaml

Note: I allowed proto methods by using this library: `@handlebars/allow-prototype-access`. Also I downgraded Handlebars version to 4.5.3 but still getting this error.

**Comment by UziTech** [comment]
Looks like an issue for handlebars or whichever repo you got `bot.users.cache.get` from
