### ISSUE TITLE
Incompatible Type Engine when using Version 6 in TypeScript project

### ISSUE THREAD

**Issue by PascalHonegger** [express-handlebars/express-handlebars#240]
I updated to the latest version of express-handlebars in my TypeScript Project and am now getting the following error:
```
error TS2345: Argument of type 'Engine' is not assignable to parameter of type '(path: string, options: object, callback: (e: any, rendered?: string | undefined) => void) => void'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'object' is not assignable to type 'EngineOptions'.
      Index signature for type 'string' is missing in type '{}'.
```

for the following code:
```ts
app.engine('hbs', engine({
    extname: '.hbs',
    defaultLayout: 'default',
    helpers: {
        ...helpers
    }
}));
```

I use the latest TypeScript (`4.5.2`) and have strict mode enabled if that matters.

**Comment by nlahme** [comment]
A quick fix is to add a global.d.ts file to your project with the following content:

```js
declare module 'express-handlebars' {
  declare function engine(config?: ConfigOptions): any;
}
```

**Comment by Sparticuz** [comment]
This might be related? Using `const hbs = create(...);` and getting this linting error in `app.engine("hbs", hbs.engine);`

`Promise returned in function argument where a void return was expected. eslint(@typescript-eslint/no-misused-promises)`

So it's either a problem in the types in 6.0.2, or in the types of @types/express v4.17.13.

If I ignore the error, it transpiles and works fine.

**Comment by TravelingTice** [comment]
Getting the same problem when using the engine directly in `app.engine('.hbs', engine())`, will also fail on `Promise returned in function argument where a void return was expected. eslint(@typescript-eslint/no-misused-promises)`. Looks like in [`index.d.ts`](https://github.com/express-handlebars/express-handlebars/blob/master/types/index.d.ts#L92) the `Engine` type returns a promise while this is not expected by Express? I see it actually expects a function that returns `void` there..
