### ISSUE TITLE
Use the array in script tag

### ISSUE THREAD

**Issue by prasantdev** [express-handlebars/express-handlebars#241]
`post.js`
```js
router.get('/posts',  (req, res) => {
    res.render('bloghome', {
        posts: posts,
        cpage: 'blogs-page-nav-link'
    });
})
```
Now I want to use the `posts` in `'/posts'`
when I used like this
```html
<script>
  let poss = {{posts}};
  console.log(poss);
</script>
```
I got the error `Uncaught SyntaxError: Unexpected identifier `

Can't we use that inside the script tag?
Actually, I want to modify some elements (Like converting timestamp to Date format) before rendering inside the `#each` like

```html
         {{#each posts}}

          <div class="col blog-card">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Pop: {{this.title}}</h5>
                <p class="card-text">{{this.tags}}</p>
                <a href="/blogpost/{{this.slug}}" class="btn btn-primary">Visit</a>
                 Posted at: {{this.timestamp}}
              </div>
            </div>
          </div>

          {{/each}}
```

**Comment by UziTech** [comment]
This would be a question for the [handlebars](https://github.com/handlebars-lang/handlebars.js) repo

**Comment by prasantdev** [comment]
> This would be a question for the [handlebars](https://github.com/handlebars-lang/handlebars.js) repo

Thanks 
I got a solution from [StackOverflow](https://stackoverflow.com/questions/30767928/accessing-handlebars-variable-via-javascript)

1) sending as JSON instead of object 
```js
router.get('/posts',  (req, res) => {
    res.render('bloghome', {
        posts: JSON.stringify(posts),
    });
})
```
and getting in the handlebars file like
```html
<script>
 let data = JSON.parse('{{{posts}}}');
 console.log(data)
</script>
```
