### ISSUE TITLE
Helpers cannot be async functions?

### ISSUE THREAD

**Issue by askonomm** [express-handlebars/express-handlebars#278]
Any attempt at passing an async function as a Handlebars helper is met with failure since it returns `[object Promise]` and doesn't wait for the async function to complete to return the actual value. Is this a bug? Because the majority of Node.js work is async these days, so it's a bit bizarre.

**Comment by UziTech** [comment]
Express handlebars just passes the helpers to handlebars.

See https://github.com/handlebars-lang/handlebars.js/issues/1446
