### ISSUE TITLE
Snyk vulnerability

### ISSUE THREAD

**Issue by TonhaoSantos** [express-handlebars/express-handlebars#3]
Olá, estou com o seguinte apontamento de vulnerabilidade:

<img width="1141" alt="Captura de Tela 2020-04-01 às 10 09 26" src="https://user-images.githubusercontent.com/12022023/78140834-ff48bb00-7400-11ea-959e-dbbf16dde4dd.png">

Alguma posição sobre o mesmo?

**Comment by UziTech** [comment]
this is tracked here: https://github.com/wycats/handlebars.js/issues/1661


Once handlebars updates than we will update it here.

**Comment by UziTech** [comment]
fixed in v4.0.1

**Comment by TonhaoSantos** [comment]
Tks :D
