### ISSUE TITLE
can't access res.locals in express-handlebars

### ISSUE THREAD

**Issue by tin-pham** [express-handlebars/express-handlebars#324]
Let say i have this when user logged in

```js
res.locals.user = user
```

I want to access it in the express-handlebars views

```hbs
<p>{{ user.username }}</p>
```

But it return empty string, didn't give me anything, I console.log the user in the server, it there, but when i give to the res.locals i not able to access it

**Comment by UziTech** [comment]
You have to pass the data that you want to use

```js
res.render('home', res.locals);
```

**Comment by tin-pham** [comment]
I discovered that when i set res.locals in the res.render middleware, it worked 
But when i try this in another middleware, it return empty 

# This work
![image](https://user-images.githubusercontent.com/20679090/164133433-25fd0d1c-24a5-4199-befe-60391aa2a997.png)

# This not i can log 'user' to the console
![image](https://user-images.githubusercontent.com/20679090/164133639-c4032fd7-34a0-471a-a617-30f60a16a679.png)

**Comment by tin-pham** [comment]
Anyway, my apologize, i think that cookies Parser didn't read the cookie properly, i fixed it

**Comment by thanhnguyen2075** [comment]
alo bạn ơi, bạn fix được lỗi này như nào vậy
