### ISSUE TITLE
Syntactic Error in express-handlebars.js

### ISSUE THREAD

**Issue by silverfran97** [express-handlebars/express-handlebars#38]
In the file express-handlebars.js, on function ExpressHandlebars.prototype.renderView, on this.render(viewPath, context, options), exactly in the line utils.assign({}, options, { layout: undefined }), there is a comma left, and should not be there because there are not more arguments. In my case it appears in line 229 -> utils.assign({}, options, { layout: undefined })","); <-

**Comment by UziTech** [comment]
Trailing commas are allowed in all supported versions of node.  What version of node are you using?

**Comment by UziTech** [comment]
If you are not able to update node to a supported version you may pin express-handlebars to v4.0.0 to support earlier versions.

**Comment by silverfran97** [comment]
> Trailing commas are allowed in all supported versions of node. What version of node are you using?

Oh sorry i did not know that was allowed. My version of NodeJs is 7.10.1 I know that there are newer versions but I need this. Anyways y deleted the comma and all works correctly

**Comment by UziTech** [comment]
Glad to hear you got it working
