### ISSUE TITLE
Get Partials or get templates returning empty object

### ISSUE THREAD

**Issue by cyborg92** [express-handlebars/express-handlebars#392]
Hi while using methods such as getTemplates or getPartials, i am getting an empty object returned, even though partial path and view path has been defined.

Attaching app.ts below
`import express from 'express';
import { engine, create } from 'express-handlebars';
import { partials } from 'handlebars';
import * as path from 'path';
import { generateEmails } from './utils/generate-email';

const app = express();
const port = process.env.PORT || 8000;
const __dirname = path.resolve();
const partialsDir = path.join(__dirname, 'src/views/partials');
app.use('/assets', express.static(path.join(__dirname, '../public')))
app.set('view engine', 'hbs');
app.set('views', './src/views');
app.engine('hbs', engine({
  layoutsDir: path.join(__dirname, 'src/views/layouts'),
  extname: 'hbs',
  defaultLayout: 'main',
  partialsDir: [
    //  path to your partials
    path.join(__dirname, 'src/views/partials'),
  ],
}));

function getTemplates() {
  create().getTemplates(partialsDir).then(resTemplates => {
    console.log('restemplate',resTemplates);
  }).catch(error => {
    console.log(error);
  })
}

function getPartials() {
  create().getPartials({precompiled:false}).then(partialFiles => {
    console.log('partial files',partialFiles);
  }).catch(error => {
    console.log(error);
  })
}

app.use(express.static('public'))

const fakeApi = () => {
  return [
    {
      name: 'Katarina',
      lane: 'midlaner'
    },
    {
      name: 'Jayce',
      lane: 'toplaner'
    },
    {
      name: 'Heimerdinger',
      lane: 'toplaner'
    },
    {
      name: 'Zed',
      lane: 'midlaner'
    },
    {
      name: 'Azir',
      lane: 'midlaner'
    }
  ];
}

app.get('/', (req, res) => {
  getPartials();
  getTemplates();
  res.render('index', { layout: 'main', suggestedChamps: fakeApi(), listExists: true });
});

app.get('/showTemplate', async (req, res) => {
  try {
    const template = await generateEmails();
    res.status(200).send(template);
  } catch (error) {
    res.status(400).send();
  }
})

app.listen(port, () => console.log(`App listening to port ${port}`));`

and my views structure is correct too and defined via engine.

below response is being received after API route is hit

App listening to port 8000
partial files {}
restemplate {}

**Comment by UziTech** [comment]
closing as stale
