### ISSUE TITLE
problems with special characters ñáéíóú

### ISSUE THREAD

**Issue by Softman65** [express-handlebars/express-handlebars#41]
i have a spanish HTML `<p>ñáéíóú</p>` and the render output text give ``"`<p>������</p>"`

            var _path = process.pkg ? path.join(process.cwd(), 'dist', 'views') : appRoot + '/dist/views/'

            var hbs = exphbs.create({
                extname: '.hbs',
                defaultView: 'default',
                layoutsDir: path.normalize(app.path.join(_path, 'layouts')),
                partialsDir: path.normalize(app.path.join(_path, 'partials'))
            });

            localhost.get('/', function (req, res, next) {

                hbs.render(path.normalize(_path)+'home.hbs' }).then(function (output) {
                        res.send(output)
                });
        
                //res.render('home', { layout: 'default', template: 'home-template' });
            });

**Comment by Softman65** [comment]
res.render('home', { encoding:'latin1', layout: 'default', template: 'home-template' }); 
******************************************************************************************
basic change in **express-handlebars.js**:

		// Optimistically cache file promise to reduce file system I/O, but remove
		// from cache if there was a problem.
		file = cache[filePath] = new Promise(function (resolve, reject) {
			fs.readFile(filePath, function (err, file) {
				if (err) {
					reject(err);
				} else {
    312				resolve(file.toString(options.encoding) );
                                      //  resolve(file)   ->original
				}
			});
		});
other changes for option propagation:


     118	template = cache[filePath] = this._getFile(filePath, { cache: options.cache, encoding: options.encoding })	
     155	this.getTemplate(filePath, { cache: options.cache , encoding: options.encoding? options.encoding : 'utf-8' }),	
     156	options.partials || this.getPartials({ cache: options.cache, encoding: options.encoding ? options.encoding : 'utf-8' }),
     203	this.getPartials({ cache: options.cache, encoding: options.encoding ? options.encoding:'utf-8' }),
     212      encoding: options.encoding ? options.encoding:'utf-8',

**Comment by UziTech** [comment]
If you want to create a PR I would be happy to review it. 😁
