### ISSUE TITLE
bug: option `extname` is not working

### ISSUE THREAD

**Issue by xobotyi** [express-handlebars/express-handlebars#5]
```
  const hbs = exphbs.create({
    extname: '.hbs',
  });

  app
    .set('views', path.join(__dirname, '../views'))
    .disable('x-powered-by')
    .engine('handlebars', hbs.engine)
    .set('view engine', 'handlebars');
```
Above does not make engine to serve `.hbs` files.

Structure:
```
app
--loaders
-----express.ts
--views
----layouts
------main.hbs
----home.hbs
```

In case i rename all files to `.handlebars` and comment the `extname` option - everything works like a charm.

**Comment by xobotyi** [comment]
Forgot to rename the engine, sorry.

**Comment by kdekooter** [comment]
Kind request to reopen this issue, as it is not solved.

`Error: Failed to lookup view "index" in views directory`

```
const handlebars = create({
  extname: '.hbs'
})

app.engine('handlebars', handlebars.engine)
app.set('view engine', 'handlebars')

app.set('views', path.join(__dirname, '/views'))
```

**Comment by UziTech** [comment]
@kdekooter feel free to open a new issue if you believe this is still an issue.
