### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by z88kat** [express-handlebars/express-handlebars#519]
I have upgraded to version 7 and receive the following error on startup of my application.  Note: my application is ES6 and have no problems using version 6.0.6

(node:20800) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/z88kat/Development/node_modules/express-handlebars/dist/index.js:6
import ExpressHandlebars from "./express-handlebars";

The problem appears to be in the express package, but I'm not sure of the root cause.

**Comment by TravikDev** [comment]
Up. Same trouble. Same error. 
But when i add **"type": "module"** in my package.json
then i've another problem:

> import { engine } from 'express-handlebars';
>          ^^^^^^
> SyntaxError: Named export 'engine' not found. The requested module 'express-handlebars' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> ```
> import pkg from 'express-handlebars'
> const { engine } = pkg
> ```

**Comment by UziTech** [comment]
Thanks for reporting this! :100:

This should be fixed in v7.0.1

This was due to the typescript target changing from ES5 to ES2015. Typescript defaults to outputting an ESModule. I added configuration to output commonjs.
