### ISSUE TITLE
Unable to override file extension - option `extname` has no effect

### ISSUE THREAD

**Issue by kdekooter** [express-handlebars/express-handlebars#536]
I tried to override the default template extension like so:

```
const handlebars = create({
  extname: '.hbs'
})

app.engine('handlebars', handlebars.engine)
app.set('view engine', 'handlebars')

app.set('views', path.join(__dirname, '/views'))
```
The following eror occurs:

`Error: Failed to lookup view "index" in views directory`

**Comment by UziTech** [comment]
See https://github.com/express-handlebars/express-handlebars#extnamehandlebars

I think `'handlebars'` needs to change to `'.hbs'`

**Comment by kdekooter** [comment]
That did the trick. Thanks a lot!
