### ISSUE TITLE
v7.0.4 partials not found

### ISSUE THREAD

**Issue by ashil88** [express-handlebars/express-handlebars#542]
Hi.

I've just upgraded from v5 to v7 and now getting `Error: The partial xxxx could not be found` for all partials that previous worked fine.
I've console.log-ed the partials using `getPartials` in both v5 and v7 and can see differences in the paths (now double backslashes in v7) which I assume is the problem...

```
V5:
{
   headFonts: [Function: ret] {
    _setup: [Function (anonymous)],
    _child: [Function (anonymous)]
  },
  'scripts/oneTrust': [Function: ret] {
    _setup: [Function (anonymous)],
    _child: [Function (anonymous)]
  },
  'scripts/nojs': [Function: ret] {
    _setup: [Function (anonymous)],
    _child: [Function (anonymous)]
  }
}
```

```
V7:
{
  headFonts: [Function: ret] {
    _setup: [Function (anonymous)],
    _child: [Function (anonymous)]
  },
  'scripts\\oneTrust': [Function: ret] {
    _setup: [Function (anonymous)],
    _child: [Function (anonymous)]
  },
  'scripts\\nojs': [Function: ret] {
    _setup: [Function (anonymous)],
    _child: [Function (anonymous)]
  }
}
```

I couldn't see anything in the changelog which indicated changes needed to be made our code, but maybe I've missed something?

Thanks
Ashil

**Comment by UziTech** [comment]
It was probably v7 the update to glob. See their [changelog](https://github.com/isaacs/node-glob/blob/main/changelog.md#90).

**Comment by bhavin36** [comment]
I am seeing same error. What is fix for this?

**Comment by UziTech** [comment]
Can you provide your configuration so I can try to debug it?

**Comment by bhavin36** [comment]
@UziTech  
const {  create } = require("express-handlebars");
const path = require("path");

const xpsHb = create({
  defaultLayout: "main",
  extname: ".hbs",
  partialsDir: path.join(__dirname, "..", "/views/partials"),
  layoutsDir: path.join(__dirname, "..", "/views/layouts"),
});

app.engine("hbs", xpsHbs.engine);`
`

**Comment by ashil88** [comment]
@bhavin36 I just upgraded to v6 for now. As @UziTech suggested, it is more than likely related to the glob upgrade in v7 but needed more time to debug and find a fix. A quick glance at the glob docs suggests that maybe setting `windowsPathsNoEscape` option might resolve the issue but I haven't tested yet...

**Comment by bhavin36** [comment]
Turns out all the partials references needs to be updated. for the following structure
![image](https://user-images.githubusercontent.com/33784509/231214750-910500de-40c6-4bf0-82fd-1b4a865b9728.png)
These partials will work - {{> [folder\\p2]}} OR {{> p1]}}
But this partial(s) will not work (which was working prior to v7.x.x) {{> folder/p2}}
@UziTech

**Comment by xNifty** [comment]
Looks like it, as that's the same thing I noticed.  On my Windows machine where I do my work, the old way of loading partials bombs out, but on the Ubuntu machine that I push edits to that hosts it the partials still load just fine using the {{> folder/partial}} scheme.

It's just the Windows machine that I had to tweak the partials to get them loading, as the {{> folder/partial}} doesn't work there.

**Comment by bhavin36** [comment]
the APP is on AWS Openshift. However, development and testing is done on windows....

**Comment by UziTech** [comment]
I'll try to write some tests to figure this out. It looks like @ashil88 is correct that `windowsPathsNoEscape` glob option should fix this.
