### ISSUE TITLE
How to render a template to a string i/o the response?

### ISSUE THREAD

**Issue by kdekooter** [express-handlebars/express-handlebars#561]
In this case for rendering an email body.

**Comment by UziTech** [comment]
Use [handlebars](https://github.com/handlebars-lang/handlebars.js). That is the template engine used by express-handlebars to hook into the view rendering system of express.

**Comment by kdekooter** [comment]
How can we leverage the layout concept, as I understand this is an express-handlebars feature?

**Comment by UziTech** [comment]
You can use the [renderView](https://github.com/express-handlebars/express-handlebars#renderviewviewpath-optionscallback-callback) method to return a string. That method should use the layouts and partials.

**Comment by UziTech** [comment]
Or if you use nodemailer to send emails you can use [nodemailer-express-handlebars](https://www.npmjs.com/package/nodemailer-express-handlebars) middleware

**Comment by kdekooter** [comment]
@UziTech Thanks for the swift response!
