### ISSUE TITLE
Post process html after res.render and before res.send

### ISSUE THREAD

**Issue by jfoclpf** [express-handlebars/express-handlebars#566]
After [checking](https://stackoverflow.com/a/71524346/1243247) in Stackoverflow and tested myself, I realized this code does indeed work

```js
app.get("/myUrl", (req, res) => {
  res.render(
    'template',
    dataObject,
    (err, rawHtml) => {
      if(!err) {
        console.log(rawHtml)
        res.send(rawHtml)
      }
    }
  )
})
```

But I got puzzled because [documentation](https://github.com/express-handlebars/express-handlebars#renderfilepath-context-options) does not mention any callback for method `render`, nor the [code](https://github.com/express-handlebars/express-handlebars/blob/fc27f6912cee219e28680ea4c42e4a89053baac1/lib/express-handlebars.ts#L183).

Could you kindly therefore clarify if `render` method is supposed to have (at least it works) a callback function? BTW, this is extremely useful, for example I will be using it for html minification.

**Comment by UziTech** [comment]
That render method is from express not express-handlebars. Here is the documentation for it: https://expressjs.com/en/4x/api.html#res.render

**Comment by jfoclpf** [comment]
@UziTech interesting,  but how node decides which to use?

**Comment by jfoclpf** [comment]
@UziTech interesting,  but how node decides which to use?

Edit: now I see, render is from the ExpressHandlebars instance
