### ISSUE TITLE
How to Pass Data to a Layout or Partial

### ISSUE THREAD

**Issue by thecodeclimber** [express-handlebars/express-handlebars#58]
I want to pass a list of links to my header partial (which I use in my main layout).  My goal is to pass this array as data to my partial and then use `each` to loop over and output that data.  

How can I do this?

Thanks.

**Comment by UziTech** [comment]
You should be able to pass it as a second parameter

```js
res.render(view, { links }, (err, html) => {
	res.send(html);
}
```

Can you provide some code that isn't working?

**Comment by UziTech** [comment]
I'm going to close this as no response. If this is still an issue feel free to reopen it and provide more information.

**Comment by absemetov** [comment]
I have /views/partial/product.hbs how to pass data to this partial?
```
{#each products as |product|}}
   {{> product}}
{{/each}}
```

**Comment by absemetov** [comment]
I solve it!
` {{> product product=product}}`
