### ISSUE TITLE
Type 'boolean' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by biQte** [express-handlebars/express-handlebars#612]
When defining a handlebarOptions I want to set defaultLayout in viewEngine to false as it is specified [here](https://github.com/express-handlebars/express-handlebars#configuration-and-defaults:~:text=You%20can%20also%20use%20a%20falsy%20value%20when%20creating%20the%20engine%20to%20make%20using%20no%20layout%20a%20default%20e.g.%20app.engine(%27.hbs%27%2C%20exphbs(%7BdefaultLayout%3A%20false%7D))%3B). 

```ts
const handlebarOptions: hbs.NodemailerExpressHandlebarsOptions = {
  viewEngine: {
    extName: ".handlebars",
    partialsDir: path.resolve("../emails"),
    defaultLayout: false,
  },
  viewPath: path.resolve("../emails"),
  extName: ".handlebars",
};
```

**Comment by UziTech** [comment]
That should work. The type of `defaultLayout` is `string|false`

https://github.com/express-handlebars/express-handlebars/blob/78d4425c843a7834ed5a932c01de0c2bad06fcbb/types/index.d.ts#L78

**Comment by biQte** [comment]
Actually the problem was here:
```ts
extName: ".handlebars"
```
extName should be extname, I watched some misguiding tutorial but when headed for docs I was how to do it the right way.
After that change everything works fine.
