### ISSUE TITLE
TypeError: handlebars is not a function

### ISSUE THREAD

**Issue by Carloswelliton** [express-handlebars/express-handlebars#651]
my code does not work, bc it cant run express-handlebars

my code:
const express = require("express");
const app = express();
const handlebars = require("express-handlebars");

//Config
    //Template Engine
    app.engine("handlebars", handlebars({defaultLayout: "main"}))
    app.set("view engine", "handlebars")

app.listen(8081, function(){
    console.log("Online Server")
})

**Comment by UziTech** [comment]
We don't use default exports any more. You were probably looking at an old tutorial. See https://github.com/express-handlebars/express-handlebars#basic-usage
