### ISSUE TITLE
Cannot find module './types'

### ISSUE THREAD

**Issue by A-Margaryan** [express-handlebars/express-handlebars#654]
Hi dear "express-handlebars" team, when I deployed my app, this problem with module "./types" in "express-handlebars/dist/index.js" occured.

Sep 20 11:41:16 AM  Error: Cannot find module './types'
Sep 20 11:41:16 AM  Require stack:
Sep 20 11:41:16 AM  - /opt/render/project/src/node_modules/express-handlebars/dist/index.js

**Comment by UziTech** [comment]
Can you create a minimal repo with code that reproduces this?

**Comment by A-Margaryan** [comment]
I used nodemailer-express-handlebars, which use express-handlebars itself.


![Screenshot 2023-09-21 121508](https://github.com/express-handlebars/express-handlebars/assets/145031482/faf7ebb6-a81b-46b7-88c5-03384525f887)
![Screenshot 2023-09-21 123227](https://github.com/express-handlebars/express-handlebars/assets/145031482/77c430a1-f9fa-407a-a4c2-8ccef2fe0137)
