### ISSUE TITLE
Handlebars clear/reset cache

### ISSUE THREAD

**Issue by titus7lite** [express-handlebars/express-handlebars#9]
(Reposting from old repo)
Hi,

i am trying to find a way to clear/reset the cache of views in order to allocate/hotswap newly created changes during runtime. I cant seem to find a way to do it as it looks to be protected. Did i miss something and such a functionality is currently achievable somehow? or should i fork the repo and make the cache puplic?

appreciate any help, thank you in advance

**Comment by UziTech** [comment]
It looks like the cache is stored in `instance._fsCache` it is meant to be private but there is nothing stopping you from editing it manually. You can also turn the cache off with the option `cache: false` and implement your own cache.

**Comment by UziTech** [comment]
A PR to make the cache public or add a way to reset it would be fine :+1:

**Comment by fineon** [comment]
Revisiting this issue since I noticed the cache served to my view is old and there's no clear way to clear the cache or control it. 
I am wondering if we have any ideas for clearing the cache?

**Comment by UziTech** [comment]
I think we just need a public method to set `_fsCache` to an empty object. If you want to create a PR for that it would be much appreciated 😁👍

Don't forget to update types and add tests.

**Comment by fineon** [comment]
Okay sure. I'm still new to TypeScript, and the codebase in general so it will take me a while to understand the codebase. I'll suggest something. Thanks!
