### ISSUE TITLE
Catch error in helpers 

### ISSUE THREAD

**Issue by tniemann** [express-handlebars/express-handlebars#92]
Hi,

I have some helpes which I use like this:

```
app.engine(
  'hbs',
  expressHbs({
    extname: 'hbs',
    defaultLayout: 'main',
    layoutsDir: path.join(__dirname, '/views/layouts'),
    partialsDir: path.join(__dirname, '/views/partials'),
    helpers: handlebars
  })
)
```

The issue is now when an error is raised in one of these methods it gets not caught in the express error function.

```
// Express Error middleware
// no stack traces leaked to user
app.use(async (err, req, res) => {
  response.sendErrorPage(res, 500)
})

//Node's uncaughtException handler
process.on('uncaughtException', async  (err) => {
  response.sendErrorPage(res, 500)
});
```

Is there a way to catch this error and show a custom error page?

Thx

**Comment by UziTech** [comment]
have you tried using a try/catch block

```
try {
  res.render(...)
} catch (e) {
  next(e)
}
```

**Comment by tniemann** [comment]
Yes.. of course. It is not caught their!

**Comment by UziTech** [comment]
Sounds like an issue with the helper functions. Can you provide the source for the helper functions?

**Comment by tniemann** [comment]
Sure.

```
exports.formatCurrency = (locale, currency, value) => {
  return Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currency
  }).format(value / 100)
}
```

To get the error I had just put "de_de"  for "locale".

**Comment by tniemann** [comment]
Just to make sure. I can try catch each function but I would like to have it at one place.

**Comment by UziTech** [comment]
Can you provide the way you call `res.render`?

**Comment by tniemann** [comment]
`return res.render('page', {})`

**Comment by UziTech** [comment]
If you use a callback you should be passed the error in the first parameter.

```js
res.render(file, data, (err, html) => {
  if (err) {
    next(err);
  }
	...
})
```

**Comment by tniemann** [comment]
Ok. But why it is not caught in the express error handler.

```
app.use(async (err, req, res) => {

  response.sendErrorPage(res, 500)
})
```

**Comment by UziTech** [comment]
You controller (`PaymentController.payment`) should have three parameters (`req`, `res`, and `next`) Calling `next` with anything other than `undefined` will send it to the error handler.

Reading the [Express Error Handling docs](https://expressjs.com/en/guide/error-handling.html) might help.
