### ISSUE TITLE
How do I use inline partials with express-handlebars and a default layout?

### ISSUE THREAD

**Issue by martisj** [express-handlebars/express-handlebars#93]
layouts/pdf.hbs
```hbs
<!DOCTYPE html>
<html lang="no">

<head>
  <title>{{pageTitle}} - Dagens</title>
  {{#> css}}
    <style>body {background-color: red; }</style>
  {{/css}}
</head>

<body>
  {{{ body}}}
</body>

</html>
```

views/page.hbs
```hbs
{{#> layouts/pdf}}
  {{#*inline "css"}}
    <style>body {background-color: white}</style>
  {{/inline}}
  <h1>The first page</h1>
{{/layouts/pdf}}
```

Gives a background–color of red when rendering `views/pages.hbs`
Where I learned that this was possible: https://cloudfour.com/thinks/the-hidden-power-of-handlebars-partials/#fnref-4803-1

**Comment by UziTech** [comment]
You can read how to do it in the [docs](https://github.com/express-handlebars/express-handlebars#layouts)

**Comment by martisj** [comment]
I read the layout section, however `inline partials` are not mentioned in the docs. The Handlebars version shipped with express-handlebars supports inline partials (https://handlebarsjs.com/guide/partials.html#inline-partials). Do you use them in your own templates @UziTech ?

**Comment by UziTech** [comment]
I do not use inline partials. It looks like you are not adding the partial to your layout anywhere (`{{> css}}`).

When using a default layout `express-handlebars` compiles the page then compiles the layout with the output from the page in the `body` variable.

I don't think there is a way to have an inline partial defined and used in different files. (That is part of the reason it is called an inline partial)

**Comment by martisj** [comment]
Gotcha! Thanks for the reply @UziTech. I ended up using: https://github.com/defunctzombie/handlebars-extend-block to make it work 👏
