### ISSUE TITLE
Express JS can`t find views directory in production mode

### ISSUE THREAD

**Issue by Iliakra** [express-handlebars/express-handlebars#97]
Hello! I am new in Express-handlebars and I can`t solve a problem. I indicate error 404 on my web-page by using handlebar template. In development mode it works fine, but in production mode it shows this: 
"Error: Failed to lookup view "error" in views directory "C:\.......\dash-service\dist\views"

So, it cannot find the necessary template (error.handlebars) in Views folder and it happens only in production mode. And there is no Views folder in dist (look please on my ScreenShot below).

This is the part of my app.js:

app.engine('handlebars', handlebars({defaultLayout: 'main', extname: ".handlebars",  layoutsDir: "views / layouts /"}));
app.set('views', path.join(__dirname, "views"));
app.set('view engine', 'handlebars');
app.enable('view cache');

app.use(function (err, req, res, next) {
  res.status(err.status || 500);
  res.render("error",{
    ...dictionary.error,
    title:(err.status || 500),
    error:req.app.get("env") === "development" ? err : {}, 
  });
});

Project folders:
![Screenshot_1](https://user-images.githubusercontent.com/51176758/97695022-7556f280-1ab4-11eb-8235-03d05f0fc214.png)

#

Command for development mode in package.json: "dev": "set OPENSSL_CONF=&&set NODE_ENV=development&&npm-run-all server",

Command for production mode in package.json: "prod": "set OPENSSL_CONF=&&set NODE_ENV=production&&npm-run-all clean build server:prod",

Whats the problem??

**Comment by UziTech** [comment]
How do you create your dist folder?

**Comment by UziTech** [comment]
You have to copy the views folder to your dist folder.

I'm going to close this since it is not something that needs to be fixed in express-handlebars.
